### ISSUE TITLE
Unable to add new account after upgrading from 5.5 to 5.6

### ISSUE THREAD

**Issue by abrarreddragon** [orangehrm/orangehrm-os-mobile#66]
I just upgraded from OrangeHRM 5.5 to 5.6 and now all the admin accounts cannot add any new user. Getting error Unauthorized.

Here is the log

[2024-01-30T11:08:31.603928-08:00] orangehrm.ERROR: Unauthorized [] []
[2024-01-30T11:08:31.605561-08:00] orangehrm.ERROR: #0 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/event-dispatcher/EventDispatcher.php(230): OrangeHRM\Core\Subscriber\ApiAuthorizationSubscriber->onControllerEvent(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...', Object(OrangeHRM\Framework\Event\EventDispatcher)) #1 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\ControllerEvent)) #2 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/http-kernel/HttpKernel.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...') #3 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(OrangeHRM\Framework\Http\Request), 1) #4 /home/dh_x5gcja/hrm.appfiniti.us/src/lib/framework/Framework.php(156): Symfony\Component\HttpKernel\HttpKernel->handle(Object(OrangeHRM\Framework\Http\Request), 1, true) #5 /home/dh_x5gcja/hrm.appfiniti.us/web/index.php(41): OrangeHRM\Framework\Framework->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #6 {main} [] []

**Comment by abrarreddragon** [comment]
Posted this issue in the correct section
